import sqlite3
con = sqlite3.Connection("MySchool.db")
c = con.cursor()
# # con.execute("DROP TABLE Students")
# # con.commit()
# # con.execute("CREATE TABLE Students (id integer primary key , FirstName text , LastName text , BirthYear integer , ClassRoom text)")
# # con.execute("INSERT INTO Students (FirstName , LastName , BirthYear , ClassRoom) VALUES ('Ahmed' , 'Raed' , 1999 , '2B')")
# # con.execute("CREATE TABLE Teachers (id integer primary key , FirstName text , LastName text , BirthYear integer , Subject text)")
# # #con.execute("INSERT INTO Teachers (FirstName , LastName , BirthYear , Subject) VALUES ('wael' , 'elgzar' , 1970 , 'arabic')")
# # #con.execute("CREATE TABLE Employees (id integer primary key , FirstName text , LastName text , BirthYear integer , Department text)")
# # con.execute("INSERT INTO Employees (FirstName , LastName , BirthYear , Department) VALUES ('ibrahim' , 'eldaly' , 1988 , 'transportation')")
# # con.commit()
mydata=con.execute("SELECT * FROM Students")
#mydata=con.execute("SELECT * FROM Teachers")
#mydata=con.execute("SELECT * FROM Employees")
print(mydata.fetchall())
#data = open("MySchool.db")
#print(data.read())
#data.close()
